-- MySQL Script generated by MySQL Workbench
-- 03/01/17 13:33:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(155) NOT NULL,
  `price` VARCHAR(155) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pisos_has_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pisos_has_contacto` (
  `pisos_id` INT NOT NULL,
  `contacto_id` INT NOT NULL,
  PRIMARY KEY (`pisos_id`, `contacto_id`),
  INDEX `fk_pisos_has_contacto_contacto1_idx` (`contacto_id` ASC),
  INDEX `fk_pisos_has_contacto_pisos_idx` (`pisos_id` ASC),
  CONSTRAINT `fk_pisos_has_contacto_pisos`
    FOREIGN KEY (`pisos_id`)
    REFERENCES `mydb`.`pisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pisos_has_contacto_contacto1`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `mydb`.`contacto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
